/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aave from "./AAVE";
export type { aave };
import type * as dsProxy from "./DSProxy";
export type { dsProxy };
import type * as gmx from "./GMX";
export type { gmx };
import type * as common from "./common";
export type { common };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as permissions from "./permissions";
export type { permissions };
import type * as stub from "./stub";
export type { stub };
