/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as action from "./action";
export type { action };
import type * as auth from "./auth";
export type { auth };
import type * as registry from "./registry";
export type { registry };
