/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReader__factory } from "./IReader__factory";
export { MockReader__factory } from "./MockReader__factory";
