/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  AaveHelper,
  AaveHelperInterface,
} from "../../../../../contracts/AAVE/AAVEProtocol/helpers/AaveHelper";

const _abi = [
  {
    inputs: [],
    name: "AAVE_REFERRAL_CODE",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b68061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806305a363de14602d575b600080fd5b60336047565b604051603e91906067565b60405180910390f35b604081565b600061ffff82169050919050565b606181604c565b82525050565b6000602082019050607a6000830184605a565b9291505056fea26469706673582212201b9b7b74dec5ed857f5f316bc485e6dcceaf875a1c4c3a191f09fa09d33ac6f964736f6c63430008180033";

type AaveHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AaveHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AaveHelper__factory extends ContractFactory {
  constructor(...args: AaveHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AaveHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AaveHelper__factory {
    return super.connect(runner) as AaveHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AaveHelperInterface {
    return new Interface(_abi) as AaveHelperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AaveHelper {
    return new Contract(address, _abi, runner) as unknown as AaveHelper;
  }
}
