/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dsProxySol from "./DSProxy.sol";
export type { dsProxySol };
import type * as proxySol from "./proxy.sol";
export type { proxySol };
