/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAaveProtocolDataProvider } from "./IAaveProtocolDataProvider";
export type { IL2Pool } from "./IL2Pool";
export type { IPool } from "./IPool";
export type { IPoolAddressesProvider } from "./IPoolAddressesProvider";
