/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as depositSol from "./Deposit.sol";
export type { depositSol };
import type * as gmxShort from "./GMXShort";
export type { gmxShort };
