/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveInterfaces from "./AAVEInterfaces";
export type { aaveInterfaces };
import type * as aaveProtocol from "./AAVEProtocol";
export type { aaveProtocol };
