/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./Mock";
export type { mock };
import type * as createShortSol from "./createShort.sol";
export type { createShortSol };
