/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testImplementationSol from "./testImplementation.sol";
export type { testImplementationSol };
