/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockExchangeRouterSol from "./MockExchangeRouter.sol";
export type { mockExchangeRouterSol };
import type * as mockReaderSol from "./MockReader.sol";
export type { mockReaderSol };
export type { MockERC20 } from "./MockERC20";
export type { MockUniswapSwap } from "./MockUniswapSwap";
