/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDSProxy,
  IDSProxyInterface,
} from "../../../contracts/interfaces/IDSProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IDSProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IDSProxyInterface {
    return new Interface(_abi) as IDSProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDSProxy {
    return new Contract(address, _abi, runner) as unknown as IDSProxy;
  }
}
