/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dsAuthSol from "./DSAuth.sol";
export type { dsAuthSol };
import type * as authSol from "./auth.sol";
export type { authSol };
export type { DSAuthority } from "./DSAuthority";
