/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestImplementation } from "./TestImplementation";
export type { TestImplementationV2 } from "./TestImplementationV2";
