/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dsAuthSol from "./DSAuth.sol";
export * as authSol from "./auth.sol";
export { DSAuthority__factory } from "./DSAuthority__factory";
